export const authActions = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_PROFILE_ERROR: 'UPDATE_PROFILE_ERROR',
};

export const threadsActions = {
  ADD_THREAD: 'ADD_THREAD',
  ADD_THREAD_ERROR: 'ADD_THREAD_ERROR',
  REMOVE_ELEMENT: 'REMOVE_ELEMENT',
  REMOVE_ELEMENT_ERROR: 'REMOVE_ELEMENT_ERROR',
};
